kind = "mobile"
previewPath = "/"
title = "MX Player"
version = "1.0.0"
id = "artifacts/mx-player"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
localPort = 22086
name = "expo"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/mx-player run dev"

[services.env]
PORT = "22086"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/mx-player", "run", "build"]
run = ["pnpm", "--filter", "@workspace/mx-player", "run", "serve"]
