# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

# For more details about Gradle configuration:
# https://docs.gradle.org/current/userguide/build_environment.html

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# React Native architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# React Native new architecture
newArchEnabled=false

# Hermes
hermesEnabled=true

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# react-native-video Android extension flags.
RNVideo_useExoplayerIMA=false
RNVideo_useExoplayerSmoothStreaming=true
RNVideo_useExoplayerDash=true
RNVideo_useExoplayerHls=true
RNVideo_useExoplayerRtsp=false
RNVideo_buildFromMedia3Source=false
