import { StyleSheet } from "react-native";
import {
  QUEUE_ITEM_LAYOUT_HEIGHT,
  UP_NEXT_LANDSCAPE_PAGE_SIZE,
  UP_NEXT_SEPARATOR_HEIGHT,
} from "./player.constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  errorContainer: {
    flex: 1,
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  errorText: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Inter_500Medium",
  },
  closeBtn: {
    backgroundColor: "#00B4FF",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  closeBtnText: {
    color: "#fff",
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
  },
  hiddenMediaView: {
    opacity: 0.02,
  },
  videoViewport: {
    overflow: "hidden",
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
  },
  videoFrame: {
    overflow: "hidden",
    backgroundColor: "#000",
  },
  audioModeCanvas: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
  },
  audioModeGlow: {
    position: "absolute",
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: "rgba(75,163,255,0.16)",
    shadowColor: "#4BA3FF",
    shadowOpacity: 0.28,
    shadowRadius: 42,
    shadowOffset: { width: 0, height: 10 },
  },
  audioModeHero: {
    width: "100%",
    maxWidth: 380,
    alignItems: "center",
    paddingHorizontal: 22,
    paddingVertical: 28,
    borderRadius: 28,
    backgroundColor: "rgba(8,10,14,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    gap: 10,
  },
  audioModeDisc: {
    width: 154,
    height: 154,
    borderRadius: 77,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(75,163,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.2)",
  },
  audioModeDiscInner: {
    width: 110,
    height: 110,
    borderRadius: 55,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(11,15,24,0.92)",
  },
  // Fix #9: Full-disc album art
  audioModeArt: {
    width: 154,
    height: 154,
    borderRadius: 77,
  },
  audioModeEyebrow: {
    color: "#7FC4FF",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  audioModeTitle: {
    color: "#fff",
    fontSize: 24,
    lineHeight: 30,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  audioModeMeta: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    textAlign: "center",
  },
  audioWaveRow: {
    position: "absolute",
    left: 28,
    right: 28,
    bottom: 152,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
  },
  audioWaveBar: {
    width: 6,
    borderRadius: 999,
    backgroundColor: "#4BA3FF",
  },
  nightOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.28)",
  },
  lockUnlockBtn: {
    position: "absolute",
    top: 18,
    alignSelf: "center",
    left: "50%",
    transform: [{ translateX: -44 }],
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.62)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  lockUnlockLabel: {
    color: "rgba(255,255,255,0.75)",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0.4,
  },
  lockFullOverlay: {
    zIndex: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  lockIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(0,0,0,0.55)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  playerStateOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  playerStateCard: {
    width: "100%",
    maxWidth: 320,
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 22,
    paddingVertical: 22,
    borderRadius: 24,
    backgroundColor: "rgba(8,10,14,0.88)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  playerStateIcon: {
    width: 58,
    height: 58,
    borderRadius: 14,
    marginBottom: 2,
  },
  playerStateTitle: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
  },
  playerStateMessage: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 12,
    lineHeight: 17,
    fontFamily: "Inter_500Medium",
    textAlign: "center",
  },
  playerStateButton: {
    marginTop: 6,
    minHeight: 40,
    paddingHorizontal: 18,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2594FF",
  },
  playerStateButtonPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  playerStateButtonText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  resumePromptOverlay: {
    position: "absolute",
    right: 20,
    bottom: 100,
    zIndex: 6,
    width: 240,
  },
  resumePromptStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 12,
    backgroundColor: "rgba(10,12,18,0.95)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  resumePromptInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  resumePromptLabel: {
    color: "#7FC4FF",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
  },
  resumePromptTime: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  resumeStartOverBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  resumeStartOverText: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  resumeBtnPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.96 }],
  },
  resumeCountdownTrack: {
    height: 3,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
  },
  resumeCountdownFill: {
    height: "100%",
    backgroundColor: "#2594FF",
    borderBottomLeftRadius: 14,
  },
  hudWrap: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 80,
  },
  hud: {
    minWidth: 190,
    maxWidth: 300,
    width: "68%",
    alignItems: "center",
    gap: 8,
  },
  hudIconRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  hudTitle: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textShadowColor: "rgba(0,0,0,0.85)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  hudLabel: {
    color: "#fff",
    fontSize: 22,
    fontFamily: "Inter_700Bold",
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.9)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  hudTrack: {
    width: "100%",
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.14)",
    overflow: "hidden",
  },
  hudFill: {
    height: "100%",
    borderRadius: 999,
    backgroundColor: "#4BA3FF",
  },
  doubleTapSeekWrap: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: "45%",
    justifyContent: "center",
    zIndex: 7,
  },
  doubleTapSeekLeft: {
    left: 0,
    alignItems: "flex-start",
    paddingLeft: 28,
  },
  doubleTapSeekRight: {
    right: 0,
    alignItems: "flex-end",
    paddingRight: 28,
  },
  doubleTapSeekBubble: {
    minWidth: 132,
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.36)",
  },
  doubleTapSeekChevronRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
  },
  doubleTapSeekLabel: {
    color: "#fff",
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.5,
    textAlign: "center",
    textShadowColor: "rgba(0,0,0,0.82)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 5,
  },
  sideGestureMessageWrap: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "48%",
    alignItems: "center",
    zIndex: 4,
  },
  sideGestureMessageText: {
    color: "#93C5FD",
    fontSize: 28,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0,
    textShadowColor: "rgba(0,0,0,0.72)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  sideGestureMessageBrightness: {
    color: "#FDE68A",
  },
  // VLC-style full-height side gesture panels
  vlcPanel: {
    position: "absolute",
    top: "24%",
    bottom: "24%",
    width: 78,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 3,
  },
  vlcPanelLeft: {
    left: 10,
  },
  vlcPanelRight: {
    right: 10,
  },
  vlcContent: {
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 4,
  },
  vlcDirectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  vlcDirectionLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 10,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
  },
  vlcDirectionLabelActive: {
    color: "rgba(255,255,255,0.82)",
  },
  vlcBarTrack: {
    width: 8,
    height: 132,
    borderRadius: 999,
    backgroundColor: "rgba(0,0,0,0.32)",
    justifyContent: "flex-end",
    position: "relative",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.24)",
  },
  vlcBarFill: {
    width: "100%",
    borderRadius: 999,
    minHeight: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.38,
    shadowRadius: 3,
  },
  vlcBarTick: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  vlcValue: {
    color: "#93C5FD",
    fontSize: 24,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0,
  },
  vlcValueBrightness: {
    color: "#FDE68A",
  },
  vlcUnit: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    letterSpacing: 0,
  },
  transitionBanner: {
    position: "absolute",
    top: "18%",
    alignSelf: "center",
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "rgba(0,0,0,0.7)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    minWidth: 220,
    maxWidth: "82%",
  },
  transitionLabel: {
    color: "#7FC4FF",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
  },
  transitionTitle: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Inter_600SemiBold",
  },
  screenshotToastWrap: {
    position: "absolute",
    top: "18%",
    right: 16,
    alignItems: "flex-end",
  },
  screenshotToast: {
    width: 180,
    borderRadius: 20,
    backgroundColor: "rgba(10,12,18,0.92)",
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  screenshotToastTitle: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  screenshotToastImage: {
    width: "100%",
    aspectRatio: 16 / 9,
    borderRadius: 14,
    backgroundColor: "#111",
  },
  screenshotToastHint: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 11,
    fontFamily: "Inter_400Regular",
  },
  upNextWrap: {
    position: "absolute",
    zIndex: 3,
  },
  upNextWrapSide: {
    top: "50%",
    right: 16,
    maxHeight: "58%",
    transform: [{ translateY: -180 }],
    width: 280,
  },
  upNextWrapBottom: {
    top: 92,
    left: 16,
    right: 16,
    bottom: 183,
  },
  upNextCard: {
    flex: 1,
    borderRadius: 24,
    backgroundColor: "rgba(8,10,14,0.86)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    padding: 14,
    gap: 10,
  },
  upNextHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  upNextTitle: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  upNextCount: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  upNextScroll: {
    flex: 1,
    minHeight: 0,
  },
  upNextScrollLandscape: {
    flex: 0,
    height:
      QUEUE_ITEM_LAYOUT_HEIGHT * UP_NEXT_LANDSCAPE_PAGE_SIZE -
      UP_NEXT_SEPARATOR_HEIGHT,
  },
  upNextList: {
    paddingBottom: 4,
  },
  upNextSeparator: {
    height: UP_NEXT_SEPARATOR_HEIGHT,
  },
  upNextItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    minHeight: 68,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  upNextItemActive: {
    backgroundColor: "rgba(111,96,255,0.22)",
    borderWidth: 1,
    borderColor: "rgba(151,139,255,0.32)",
  },
  upNextItemPressed: {
    backgroundColor: "rgba(75,163,255,0.18)",
    transform: [{ scale: 0.98 }],
  },
  upNextIndex: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(75,163,255,0.2)",
  },
  upNextIndexText: {
    color: "#BFE4FF",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  upNextTextBlock: {
    flex: 1,
    gap: 2,
  },
  upNextItemTitle: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
  },
  upNextItemMeta: {
    color: "rgba(255,255,255,0.66)",
    fontSize: 11,
    fontFamily: "Inter_400Regular",
  },
  upNextActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(75,163,255,0.18)",
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.24)",
  },
  upNextActionBtnPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  upNextPager: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  upNextPagerBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minWidth: 92,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: "rgba(75,163,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.18)",
  },
  upNextPagerBtnPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  upNextPagerBtnDisabled: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderColor: "rgba(255,255,255,0.08)",
  },
  upNextPagerBtnText: {
    color: "#EAF6FF",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  upNextPagerBtnTextDisabled: {
    color: "rgba(234,246,255,0.35)",
  },
  upNextPagerText: {
    color: "rgba(255,255,255,0.64)",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  upNextActionText: {
    color: "#EAF6FF",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  suggestedSection: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.08)",
    paddingTop: 6,
    marginTop: 4,
  },
  suggestedHeader: {
    color: "rgba(255,255,255,0.45)",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    paddingHorizontal: 12,
    paddingBottom: 4,
  },
  centerPanelWrap: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingTop: 86,
    paddingBottom: 132,
  },
  infoPanel: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(8,10,14,0.82)",
    overflow: "hidden",
  },
  infoPanelCentered: {
    width: "100%",
    maxWidth: 760,
    maxHeight: "100%",
  },
  trimPanel: {
    width: "100%",
    maxWidth: 620,
    maxHeight: "100%",
  },
  infoScrollContent: {
    padding: 16,
    gap: 16,
    paddingBottom: 24,
  },
  infoHero: {
    gap: 6,
  },
  infoEyebrow: {
    color: "#7FC4FF",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
    letterSpacing: 0.9,
  },
  infoTitle: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Inter_700Bold",
  },
  infoSubtitle: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 18,
  },
  infoSection: {
    gap: 10,
  },
  infoSectionTitle: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  trimTitleInput: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.18)",
    backgroundColor: "rgba(255,255,255,0.05)",
    color: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
  },
  infoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  infoCard: {
    minWidth: 120,
    flexGrow: 1,
    flexBasis: "46%",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    gap: 4,
  },
  infoCardLabel: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  infoCardValue: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_500Medium",
  },
  infoChipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  trimActionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  trimActionBtn: {
    minWidth: 120,
    flexGrow: 1,
    flexBasis: "46%",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    gap: 5,
  },
  trimActionBtnPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  trimActionTitle: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  trimActionMeta: {
    color: "#7FC4FF",
    fontSize: 12,
    fontFamily: "Inter_500Medium",
  },
  trimFooter: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  trimSecondaryBtn: {
    minHeight: 46,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  trimSecondaryBtnPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  trimSecondaryBtnText: {
    color: "#EAF6FF",
    fontSize: 13,
    fontFamily: "Inter_700Bold",
  },
  trimPrimaryBtn: {
    minHeight: 46,
    flexGrow: 1,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2594FF",
  },
  trimPrimaryBtnPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },
  trimPrimaryBtnDisabled: {
    opacity: 0.55,
  },
  trimPrimaryBtnText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  infoChip: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "rgba(127,196,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.2)",
  },
  infoChipText: {
    color: "#EAF6FF",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
  },
  sleepTimerOverlay: {
    position: "absolute",
    top: 50,
    right: 70,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    gap: 6,
    zIndex: 10,
  },
  sleepTimerText: {
    color: "#fff",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },
  upNextPopup: {
    position: "absolute",
    bottom: 100,
    right: 20,
    backgroundColor: "rgba(10,12,18,0.95)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
    padding: 12,
    width: 240,
    zIndex: 20,
  },
  upNextPopupContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  upNextPopupInfo: {
    flex: 1,
    gap: 2,
  },
  upNextPopupLabel: {
    color: "#7FC4FF",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    textTransform: "uppercase",
  },
  upNextPopupTitle: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  upNextPopupBtn: {
    backgroundColor: "#2594FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  upNextPopupBtnText: {
    color: "#fff",
    fontSize: 11,
    fontFamily: "Inter_700Bold",
  },
  upNextPopupButtons: {
    flexDirection: "row",
    gap: 8,
  },
  upNextPopupBtnRestart: {
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  upNextPopupBtnNext: {
    backgroundColor: "#2594FF",
    flex: 1,
  },
  discoveryHints: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 40,
    alignItems: "center",
    zIndex: 5,
  },
  discoveryHintLeft: {
    alignItems: "center",
    gap: 8,
  },
  discoveryHintRight: {
    alignItems: "center",
    gap: 8,
  },
  discoveryHintText: {
    color: "rgba(255,255,255,0.3)",
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase",
  },
  countdownOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 80,
  },
  countdownCard: {
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 28,
    paddingVertical: 24,
    borderRadius: 28,
    backgroundColor: "rgba(0,0,0,0.82)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    minWidth: 220,
  },
  countdownLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  countdownNumber: {
    color: "#4BA3FF",
    fontSize: 64,
    fontFamily: "Inter_700Bold",
    lineHeight: 72,
  },
  countdownTitle: {
    color: "#fff",
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    maxWidth: 240,
    textAlign: "center",
  },
  countdownCancelBtn: {
    marginTop: 8,
    paddingHorizontal: 22,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  countdownCancelText: {
    color: "#fff",
    fontSize: 14,
    fontFamily: "Inter_700Bold",
  },
  speedBadge: {
    position: "absolute",
    top: "12%",
    alignSelf: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
    backgroundColor: "rgba(37,148,255,0.88)",
    zIndex: 90,
    elevation: 6,
  },
  speedBadgeText: {
    color: "#fff",
    fontSize: 28,
    fontFamily: "Inter_700Bold",
  },
  hudOverlayCenter: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  hudCardCenter: {
    backgroundColor: "rgba(0,0,0,0.8)",
    paddingHorizontal: 30,
    paddingVertical: 20,
    borderRadius: 24,
    alignItems: "center",
    minWidth: 160,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  hudLabelCenter: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    marginBottom: 12,
  },
  hudProgressTrackCenter: {
    width: "100%",
    height: 4,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 2,
    overflow: "hidden",
  },
  hudProgressFillCenter: {
    height: "100%",
    backgroundColor: "#4BA3FF",
  },
  hudOverlaySide: {
    position: "absolute",
    top: "20%",
    bottom: "20%",
    width: 44,
    justifyContent: "center",
    zIndex: 100,
  },
  hudAdaptiveContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 22,
    padding: 4,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  hudAdaptiveTrack: {
    flex: 1,
    width: 6,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 3,
    overflow: "hidden",
    justifyContent: "flex-end",
    marginBottom: 8,
    marginTop: 8,
  },
  hudAdaptiveFill: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 3,
  },
  hudAdaptiveIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  gestureBar: {
    position: "absolute",
    top: "20%",
    width: 50,
    height: "55%",
    backgroundColor: "rgba(0,0,0,0.72)",
    borderRadius: 14,
    alignItems: "center",
    paddingVertical: 10,
    gap: 6,
    zIndex: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  gestureBarLeft: {
    left: 8,
  },
  gestureBarRight: {
    right: 8,
  },
  gestureBarTrackWrap: {
    flex: 1,
    width: 10,
    marginBottom: 4,
  },
  gestureBarTrack: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 5,
    overflow: "hidden",
    justifyContent: "flex-end",
  },
  gestureBarFill: {
    width: "100%",
    borderRadius: 5,
    minHeight: 4,
  },
  gestureBarPct: {
    fontSize: 10,
    fontFamily: "Inter_700Bold",
  },
  resumeHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },

  resumeCloseBtn: {
    padding: 2,
    borderRadius: 20,
  },

  // Fix #12: Start Over card — bottom-left, non-intrusive
  startOverCard: {
    position: "absolute",
    bottom: 110,
    left: 14,
    zIndex: 20,
    maxWidth: 240,
  },
  startOverInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(10,12,20,0.92)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  startOverTextBlock: {
    flex: 1,
    gap: 2,
  },
  startOverLabel: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 11,
    fontFamily: "Inter_500Medium",
  },
  startOverAction: {
    color: "#7FC4FF",
    fontSize: 12,
    fontFamily: "Inter_700Bold",
  },

  // Fix 4: Last-5-sec ending overlay — bottom-right
  endingOverlay: {
    position: "absolute",
    bottom: 110,
    right: 14,
    zIndex: 20,
    maxWidth: 220,
  },
  endingOverlayInner: {
    backgroundColor: "rgba(10,12,20,0.93)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(127,196,255,0.22)",
    paddingHorizontal: 14,
    paddingVertical: 11,
    gap: 4,
  },
  endingOverlayEyebrow: {
    color: "#7FC4FF",
    fontSize: 10,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  endingOverlayTitle: {
    color: "#fff",
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
  },
  endingOverlayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 2,
  },
  endingOverlayAction: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    fontFamily: "Inter_400Regular",
  },

});
