import React from "react";
import { Modal, Pressable, StyleSheet, Text, View } from "react-native";
import Feather from "react-native-vector-icons/Feather";
import type { AudioConversionFormat } from "@/services/videoAudioConversion";
type Props = { visible: boolean; title: string; format: AudioConversionFormat; progress: number; elapsedSeconds: number; busy: boolean; onFormatChange: (format: AudioConversionFormat) => void; onConvert: () => void; onCancel: () => void; };
const FORMATS: { key: AudioConversionFormat; label: string; detail: string }[] = [{ key: "mp3", label: "MP3", detail: "Most compatible" }, { key: "m4a", label: "M4A", detail: "AAC + metadata" }, { key: "aac", label: "AAC", detail: "Raw AAC stream" }];
function formatSeconds(seconds: number) { const value = Math.max(0, Math.floor(seconds || 0)); return Math.floor(value / 60) + ":" + String(value % 60).padStart(2, "0"); }
export function VideoToAudioModal({ visible, title, format, progress, elapsedSeconds, busy, onFormatChange, onConvert, onCancel }: Props) {
 return <Modal visible={visible} transparent animationType="fade" onRequestClose={onCancel}><View style={styles.backdrop}><View style={styles.card}>
  <View style={styles.header}><View style={styles.headerIcon}><Feather name="music" size={20} color="#fff" /></View><View style={styles.headerText}><Text style={styles.eyebrow}>Extract audio</Text><Text style={styles.title} numberOfLines={2}>{title}</Text></View>{!busy ? <Pressable onPress={onCancel} style={styles.close}><Feather name="x" size={20} color="#fff" /></Pressable> : null}</View>
  <Text style={styles.sectionTitle}>Output format</Text><View style={styles.formatRow}>{FORMATS.map(item => <Pressable key={item.key} disabled={busy} onPress={() => onFormatChange(item.key)} style={[styles.formatCard, item.key === format && styles.formatCardSelected]}><Text style={styles.formatLabel}>{item.label}</Text><Text style={styles.formatDetail}>{item.detail}</Text></Pressable>)}</View>
  {busy ? <View style={styles.progressSection}><View style={styles.progressHeader}><Text style={styles.progressLabel}>Converting...</Text><Text style={styles.progressValue}>{Math.round(progress * 100)}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: Math.max(2, progress * 100) + "%" }]} /></View><Text style={styles.elapsed}>Elapsed {formatSeconds(elapsedSeconds)}</Text></View> : <Text style={styles.hint}>Conversion runs locally. The original video is not modified.</Text>}
  <View style={styles.footer}><Pressable onPress={onCancel} style={styles.secondary}><Text style={styles.secondaryText}>{busy ? "Cancel" : "Close"}</Text></Pressable>{!busy ? <Pressable onPress={onConvert} style={styles.primary}><Feather name="download" size={16} color="#fff" /><Text style={styles.primaryText}>Convert</Text></Pressable> : null}</View>
 </View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop:{flex:1,backgroundColor:"rgba(0,0,0,0.72)",alignItems:"center",justifyContent:"center",padding:18}, card:{width:"100%",maxWidth:520,borderRadius:24,backgroundColor:"#10131a",borderWidth:1,borderColor:"rgba(255,255,255,0.1)",padding:18,gap:16}, header:{flexDirection:"row",alignItems:"center",gap:12}, headerIcon:{width:42,height:42,borderRadius:14,backgroundColor:"#2594FF",alignItems:"center",justifyContent:"center"}, headerText:{flex:1,gap:2}, eyebrow:{color:"#7FC4FF",fontSize:11,fontWeight:"700",textTransform:"uppercase",letterSpacing:0.8}, title:{color:"#fff",fontSize:17,fontWeight:"700"}, close:{width:38,height:38,borderRadius:19,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(255,255,255,0.07)"}, sectionTitle:{color:"#fff",fontSize:13,fontWeight:"700"}, formatRow:{flexDirection:"row",gap:10}, formatCard:{flex:1,minHeight:72,borderRadius:16,padding:12,backgroundColor:"rgba(255,255,255,0.06)",borderWidth:1,borderColor:"rgba(255,255,255,0.06)"}, formatCardSelected:{borderColor:"#4BA3FF",backgroundColor:"rgba(75,163,255,0.15)"}, formatLabel:{color:"#fff",fontSize:14,fontWeight:"700"}, formatDetail:{color:"rgba(255,255,255,0.58)",fontSize:11,marginTop:5}, hint:{color:"rgba(255,255,255,0.64)",fontSize:12,lineHeight:18}, progressSection:{gap:8}, progressHeader:{flexDirection:"row",justifyContent:"space-between"}, progressLabel:{color:"#fff",fontSize:13,fontWeight:"700"}, progressValue:{color:"#7FC4FF",fontSize:13,fontWeight:"700"}, track:{height:7,borderRadius:99,overflow:"hidden",backgroundColor:"rgba(255,255,255,0.1)"}, fill:{height:"100%",backgroundColor:"#4BA3FF",borderRadius:99}, elapsed:{color:"rgba(255,255,255,0.55)",fontSize:11}, footer:{flexDirection:"row",justifyContent:"flex-end",gap:10}, secondary:{minHeight:44,paddingHorizontal:18,borderRadius:14,alignItems:"center",justifyContent:"center",backgroundColor:"rgba(255,255,255,0.08)"},secondaryText:{color:"#EAF6FF",fontSize:13,fontWeight:"700"},primary:{minHeight:44,paddingHorizontal:20,borderRadius:14,flexDirection:"row",gap:8,alignItems:"center",justifyContent:"center",backgroundColor:"#2594FF"},primaryText:{color:"#fff",fontSize:13,fontWeight:"700"} });